version: '2'
services:
 graph:
  image: neo4j:3.0
  ports:
   - "7474:7474"
   - "7687:7687"
  volumes: 
   - "/neo4j/data:/data"
  environment: 
  - "NEO4J_AUTH=none"
 search:
  image: elasticsearch:2.4
  ports: 
   - "9200:9200"
   - "9300:9300"
  volumes: 
   - "/esdata:/usr/share/elasticsearch/data"
